repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [ --safe, --quiet ]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.9.2
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black==20.8b1 ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
        exclude: _pytest/(debugging|hookspec).py
        language_version: python3
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: python-use-type-annotations
      - id: rst-backticks
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          - flake8-typing-imports==1.9.0
          - flake8-docstrings==1.5.0
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
      - id: reorder-python-imports
        args: [ '--application-directories=.:shipengine_sdk', --py37-plus ]
